### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Seqi/firebase-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by Seqi** [comment]
Hi there,

Thanks for the interest! As suggested, I've added the MIT license with commit [4c6ef17130fe9a431d677c4895fd0da9652d4cf7](https://github.com/Seqi/firebase-zsh/commit/4c6ef17130fe9a431d677c4895fd0da9652d4cf7).

Appreciated.
